### ISSUE TITLE
Design A Super Simple Test Framework / Simulator For Testing Plays / Tactics

### ISSUE THREAD

**Issue by garethellis0** [UBC-Thunderbots/Software#768]
### Description of the task
Currently we have no way of testing the high level behavior of tactics/plays. We would like to have a very simple framework for specifying things like:
```
Set robot a at {0,0}
Set ball at {1,1}
Run tactic GrabBall 
Assert robot moves to ball
```
and similarly for plays.

Some general notes from brainstorming:
- Do not simulate collisions, physics, just step robots along the direction of their path / primitive
- Do not simulate ball motion initially
- Start with a basic one where we have simulated implementations for how the primitives move
- Move to using our firmware stack later
- Should work with the visualizer
- Should be able to run on CI
- Should be fast to run

*This ticket is for planning of work and creation of all the issues to make this happen*

*Updated Specification*
After some consideration, a test framework without physics isn't worth the effort of development because it doesn't cover most of the behavior we actually want to test, for example intercepting a ball, taking a shot, dribbling behavior.

As such we will be implementing a simple physics simulator in order to achieve the level of testing we want.

_High-level Specification:_
- Will simulate physics like collisions and ball motion, but will do so with extremely simple / no friction models so everything moves ideally.
- Should allow for firmware primitives to be simulated as well (including our firmware motion control)
- Should be able to run at least as fast as "real time"
- Should work with the Visualizer
- Should be able to run on CI (without the Visualizer)

_Tickets for v1_
The first implementation of the simulator will be able to run basic tests as gtests, with the option of displaying in the Visualizer.

- [x] #868 Set up high-level structure
- [x] #869 Decide on Physics Engine
- [x] #881  Implement and test simple `PhysicsBall`
- [x] #882  Implement and test simple `PhysicsField`
- [ ] #883  Implement and test simple `PhysicsRobot`
- [ ] TODO Implement and test simple `PhysicsTeam`
- [ ] #1046 Implement and test simple `PhysicsWorld`
- [x] #1025  Create an abstraction around the physics simulation / physics objects
- [x] #1026 Integrate physics simulation with the `SimulatorBackend`
- [x] #1028 Create a class / function used to validate simulated behaviour
- [ ] #1066 Integrate validation with the backend
- [ ] #1029 Re-enable waiting for primitives or make it optional
- [ ] #1030 Set the play being tested

### Acceptance criteria

- [ ] Create all required tickets for implementing the framework / simulator described above, being sure to reference this ticket in all of them
- [ ] Document design decisions in this ticket
